---
name: install-linux

"on":
  push: {}

permissions:
  contents: read

jobs:
  python37:
    runs-on: ubuntu-latest

    env:
      PY_SYS_INTERPRETER: python3.7

    steps:
      # ~~~~~~~~~~~~~~~~~~~~~
      # Set up
      # ~~~~~~~~~~~~~~~~~~~~~
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"

      - name: Reload Cache / pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # ~~~~~~~~~~~~~~~~~~~~~
      # Install & Test
      # ~~~~~~~~~~~~~~~~~~~~~
      - name: Install
        run: make install

      - name: Basic CLI Integration Tests
        run: |
          cr -d fetch
          cr -d rank -smg
