---
name: test

"on":
  push: {}

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Reload Cache / pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ matrix.python-version }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python-version }}-pip-

      - name: Install requirements
        run: pip install -r requirements.txt -r requirements-lint.txt

      - name: Lint
        run: PATH=~/.local/bin:$PATH make lint

      - name: Test
        run: PATH=~/.local/bin:$PATH make test

      - name: Basic CLI Integration Tests
        run: |
          ./singles.py
          ./doubles.py
          ./matchups.py thomas mal shane benji norm
