---
name: test

"on":
  push: {}

permissions:
  contents: read

jobs:
  test:
    runs-on: [self-hosted, vps76]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Count lines of source code
        run: cloc HEAD

      - name: Reload Cache / pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ matrix.python-version }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python-version }}-pip-

      - name: Install requirements
        run: pip install -r requirements.txt -r requirements-lint.txt

      - name: Lint
        run: PATH=~/.local/bin:$PATH make lint

      - name: Test
        run: PATH=~/.local/bin:$PATH make test

      - name: Basic CLI Integration Tests
        run: |
          ./singles.py
          ./doubles.py
          ./matchups.py thomas mal shane benji norm

      - name: Submit coverage report / coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -U coveralls
          PATH=~/.local/bin:$PATH coveralls --service=github
