---
name: test

"on":
  push: {}

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # - name: Count lines of source code
      #   run: cloc HEAD

      - name: Reload Cache / pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ matrix.python-version }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python-version }}-pip-

      - name: Install requirements
        run: pip install -r requirements.txt -r requirements-lint.txt

      - name: Lint
        run: make lint

      # - name: Test
      #   run: make test

      - name: Basic Tests / CLI / Integration
        run: |
          ./singles.py
          ./doubles.py
          ./matchups.py thomas mal shane benji norm
